### ISSUE TITLE
Paths_* modules cannot be found

### ISSUE THREAD

**Issue by mrkkrp** [flycheck/flycheck-haskell#82] opened 2018-01-12 08:24 UTC
As you probably know there is a way to get version of package we're building by importing a special auto-generated module that is prefixed with `Paths_`. For example, I have a project called `mmark-cli` and so I would like to write the following:

```haskell
module Main (main) where

import Paths_mmark_cli (version)

main :: IO ()
main = return ()
```

This succeeds with `stack build` but Flycheck reports an error:

```
Could not find module ‘Paths_mmark_cli’
Use -v to see a list of the files searched for.
```

Which is very unfortunate. Maybe this could be fixed somehow?

**Comment by mrkkrp** [comment] 2018-01-12 08:26
The auto-generated module is located at `.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/mmark/autogen` where `mmark` is the name of component (executable), `mmark-cli` is the name of package.

**Comment by mrkkrp** [comment] 2018-01-12 08:44
It looks like the difference is in the presence of executable name:

```
Included by Flycheck: .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/autogen
Needs to be included: .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/mmark/autogen
                                                                               ^^^^^
```

**Comment by mrkkrp** [comment] 2018-01-12 10:07
I'm also getting:

```
Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: cc1: fatal error: cabal_macros.h: No such file or directory
compilation terminated.
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
```

when I try to use CPP, namely the Cabal-generated definitions such as `VERSION_my_package`. I think the culprit may be the same.

**Comment by gahag** [comment] 2018-01-20 07:32
I'm also having this. I believe it is related to this issue in stack/cabal: https://github.com/commercialhaskell/stack/issues/3791

**Comment by gahag** [comment] 2018-01-20 07:48
I got rid of the issue, both in stack ghci and in flycheck, by changing the stack resolver from lts-10.3 to lts-9.21. It looks like the cause is a breaking change in the new cabal version.
I've also installed the flycheck-haskell package in emacs while attempting to solve the issue. Not sure if it's related.

**Comment by sergv** [comment] 2018-01-20 09:49
Great, thanks for the investigation. I'll see what I can do.

On 20 January 2018 07:48:35 GMT+00:00, gahag <notifications@github.com> wrote:
>I got rid of the issue, both in stack ghci and in flycheck, by changing
>the stack resolver from lts-10.3 to lts-9.21. It looks like the cause
>is a breaking change in the new cabal version.
>I've also installed the flycheck-haskell package in emacs while
>attempting to solve the issue. Not sure if it's related.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/flycheck/flycheck-haskell/issues/82#issuecomment-359153547

Sergey

**Comment by sergv** [comment] 2018-01-22 23:54
@mrkkrp @gahag I would apreciate if you could give [my PR](https://github.com/flycheck/flycheck-haskell/pull/83) a spin and check that it works for you.

**Comment by sergv** [comment] 2018-01-25 23:28
Should be fixed now. Please reopen if that's not the case.

**Closed by sergv** 2018-01-25 23:28 UTC

**Comment by mrkkrp** [comment] 2018-04-11 14:48
I'm experiencing this again. Now I'm on NixOS though. Anything I can do to help debug this?

**Comment by sergv** [comment] 2018-04-15 00:36
Sorry for late reply - it seems that this project generates a bit more issues that its size may suggest.

In order to be able to help you, please provide: 1. Reproducible example; 2. Output of `find <project--root> -name 'Paths_*'`; 3. Value of `flycheck-ghc-args` elisp variable in a buffer where errorneous behaviour is observed; 4. (optional) Output of the `<path to NixOS-blessed runghc> <path to flychec-haskell's get-cabal-configuration.hs> --cabal-file *.cabal` in the project's root dilectory.

On 11 April 2018 15:48:57 BST, Mark Karpov <notifications@github.com> wrote:
>I'm experiencing this again. Now I'm on NixOS though. Anything I can do
>to help debug this?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/flycheck/flycheck-haskell/issues/82#issuecomment-380479882

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mrkkrp** [comment] 2018-04-16 06:45
Huh, it looks like I can't reproduce it anymore. If I run into this again, I'll provide the info you requested!
