### ISSUE TITLE
"Opening directory: Not a directory"

### ISSUE THREAD

**Issue by hicksy994** [flycheck/flycheck-haskell#72] opened 2017-07-22 20:03 UTC
Hi, Whenever I try to do anything to do with flycheck in a Haskell buffer, I get: "Opening directory: Not a directory".

Even running flycheck-verify-setup gets this error. Any idea what might be happening?

**Comment by sergv** [comment] 2017-07-22 20:51
Can you provide a minimal reproducible test case?

If not, can you post stack trace you're getting on error? To get backtrace, do `M-x toggle-debug-on-error` before running action that throws the error.

**Comment by sergv** [comment] 2017-07-22 21:51
Okay, I can reproduce the error in my projects as well. It's actually caused by a recent PR of mine that got merged into the `flycheck` project, https://github.com/flycheck/flycheck/pull/1287. I'll try to sort it out.

**Comment by sergv** [comment] 2017-07-23 15:42
Should be fixed now as the fix is merged.

**Closed by sergv** 2017-07-23 15:42 UTC
