### ISSUE TITLE
ghc stopped checking my buffers

### ISSUE THREAD

**Issue by kuribas** [flycheck/flycheck-haskell#66] opened 2017-04-29 08:47 UTC
Hi, ghc stopped checking my buffers, but I get no error message why.  I use cabal, I have disabled stack, because I don't use it.  My ghc version is 8.2

**Comment by sergv** [comment] 2017-05-18 20:14
Hi, thanks for reporting. The issue is caused by new Cabal that's shipping with ghc - they changed API and executable that get project's configuration using Cabal-the-library do not compile any more.

I've fixed these issues in my pr.

**Comment by sergv** [comment] 2017-05-19 20:23
The issue should be fixed now.

**Closed by sergv** 2017-05-19 20:23 UTC

**Comment by kuribas** [comment] 2017-05-20 07:23
Right, it works again :+1:
