### ISSUE TITLE
`haskell-stack-ghc` is not receiving CPP args, presumably not using cabal?

### ISSUE THREAD

**Issue by slpopejoy** [flycheck/flycheck-haskell#68] opened 2017-05-26 17:33 UTC
I just upgraded flycheck as well as moved a project to GHC 8.0.2 (from 7.10.3), and CPP includes are no longer working with the checker. In my case, I define `PACT_VERSION` in my cabal:

```
  cpp-options: -DPACT_VERSION="2.2.2"
```

then have a module just to import this:

```
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE CPP #-}

module Pact.Types.Version (pactVersion) where

import Data.Text (Text)

pactVersion :: Text
pactVersion = PACT_VERSION
```

`PACT_VERSION` shows up as an undefined symbol. Output of `flycheck-compile` with `haskell-stack-ghc`:

```
stack ghc -- -Wall -no-link -outputdir /var/folders/7r/_9jtpk2j0gs7sg89099hxp0r0000gn/T/flycheck-haskell-ghc-cache5748aky -XHaskell2010 -i/Users/stuart/dev/pact/dist/build -i/Users/stuart/dev/pact/dist/build/autogen -i/Users/stuart/dev/pact/dist/build/pact/pact-tmp -i/Users/stuart/dev/pact/dist/build/bench/bench-tmp -i/Users/stuart/dev/pact/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build -i/Users/stuart/dev/pact/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/autogen -i/Users/stuart/dev/pact/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/pact/pact-tmp -i/Users/stuart/dev/pact/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/bench/bench-tmp -i/Users/stuart/dev/pact/src -i/Users/stuart/dev/pact/executables -i/Users/stuart/dev/pact/tests -i/Users/stuart/dev/pact/src/ -Wall -I/Users/stuart/dev/pact/dist/build/autogen -I/Users/stuart/dev/pact/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/autogen -optP-include -optPcabal_macros.h -hide-all-packages -package Decimal -package aeson -package ansi-wl-pprint -package async -package attoparsec -package base -package base16-bytestring -package blake2 -package bound -package bytestring -package cereal -package containers -package criterion -package data-default -package deepseq -package direct-sqlite -package directory -package ed25519-donna -package exceptions -package fast-logger -package filepath -package hashable -package hspec -package lens -package lens-aeson -package mtl -package old-locale -package optparse-applicative -package parsers -package safe -package safe-exceptions -package scientific -package semigroups -package snap-core -package snap-server -package statistics -package stm -package text -package thyme -package transformers -package trifecta -package unordered-containers -package utf8-string -package vector -package vector-space -package yaml -x hs /Users/stuart/dev/pact/src/Pact/Types/Version.hs
[1 of 1] Compiling Pact.Types.Version ( /Users/stuart/dev/pact/src/Pact/Types/Version.hs, /var/folders/7r/_9jtpk2j0gs7sg89099hxp0r0000gn/T/flycheck-haskell-ghc-cache5748aky/Pact/Types/Version.o )

/Users/stuart/dev/pact/src/Pact/Types/Version.hs:18:15: error:
    Data constructor not in scope: PACT_VERSION :: Text
```

What you'll note is that the necessary flags are missing. If I do a verbose build from stack (with `--cabal-verbose`), I see the following: 

```
2017-05-26 13:21:03.749746: [info] /Users/stuart/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --make -fbuilding-cabal-package -O -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build -odir .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build -hidir .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build -stubdir .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build -i -i.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build -isrc -i.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/autogen -I.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/autogen -I.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build '-optP-DPACT_VERSION="2.2.2"' ...
```

The `-optP-DPACT_VERSION="2.2.2"` being the missing thing. If I add that to the command invocation above from flycheck-compile (on the command line) it works.

So it would seem that the flycheck environment is not working properly with the cabal file.

**Comment by sergv** [comment] 2017-05-26 21:48
@slpopejoy Hi, thanks for report. It seems to me that the issue is caused by not considering contents of `cpp-options` cabal field. Currently only contents of `ghc-options` in considered, stored in `otherOptions` at https://github.com/flycheck/flycheck-haskell/blob/master/get-cabal-configuration.hs#L195. 

Therefore the fix should be to merge contents of `cpp-options` and `ghc-options` fields when invoking ghc. I'll prepare a patch.

**Comment by sergv** [comment] 2017-06-04 11:47
The issue should be fixed now.

**Closed by sergv** 2017-06-04 11:47 UTC
