### ISSUE TITLE
Stack based syntax checker

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck-haskell#45] opened 2015-09-07 11:55 UTC
Use `stack build` for syntax checking.

**Comment by boothead** [comment] 2015-10-19 05:27
Now that you've merged flycheck/flycheck/#752 the wrapper feature could be used for this (and for a nix-shell based version too) right?

**Comment by lunaryorn** [comment] 2015-10-19 05:30
Flycheck already includes a `stack ghc` syntax checker.  This issue tracks whether me might be able to use `stack build` successfully.  I'm not sure how that relates to https://github.com/flycheck/flycheck/pull/752…

**Comment by boothead** [comment] 2015-10-19 05:59
Ah my apologies, I thought this would be a command wrapping issue like this other one. My mistake :-)

**Comment by sergv** [comment] 2019-08-24 22:17
I'm going to close this issue to clean up the issue tracker. If you feel the issue is not resolved then please either reopen it or create a new one.

**Closed by sergv** 2019-08-24 22:17 UTC
Labels: enhancement
