### ISSUE TITLE
Flycheck-haskell hangs indefinitely on NixOS

### ISSUE THREAD

**Issue by mrkkrp** [flycheck/flycheck-haskell#89] opened 2018-06-01 10:23 UTC
This is the start of my investigation. I have found out that `flycheck-haskell-setup`, which is added like this:

```emacs-lisp
(add-hook 'flycheck-mode-hook #'flycheck-haskell-setup)
```

Causes indefinite block on opening on files. (Since I use `flycheck` in most modes, and this function doesn't check whether or not we're in `haskell-mode` that was quite a problem.)

In that function, invocation of `flycheck-haskell-configure` in particular is problematic. Also note that after I press `C-g` I find `Waiting for process to die...done` in the message buffer. Perhaps invocation of some Haskell script hangs.

I'll investigate more as I have time.

**Comment by sergv** [comment] 2018-06-02 09:58
Thanks for the report and investigation so far.

The `flycheck-haskell-configure` function basically calls `runghc get-cabal-configuration.hs` to dump cabal file for Emacs. That, in turn, calls `stack path --dist-dir` in order to determine build directory for stack. I think you can star by running `stack path --dist-dir` in your project's directory and see, whether it works. Likely, Emacs picks up wrong stack here - I recall you were tweaking paths for Nix via some kind of configurable elisp function. Perhaps this information should be propagated into `get-cabal-configuration.hs`, because otherwise it will just try to search for `stack` in `PATH`.

**Comment by sergv** [comment] 2018-06-02 10:55
Given that we generally don't know whether we're in a Haskell mode or not (e.g. user could have their own haskell-mode with unpredictable name, like `joe-haskell-mode`), it seems that we should rather alter the setup instruction. Instead of `(eval-after-load 'flycheck '(add-hook 'flycheck-mode-hook #'flycheck-haskell-setup))`, something like `(eval-after-load 'flycheck '(add-hook 'haskell-mode-hook #'flycheck-haskell-setup))` should be advertised.

**Comment by mrkkrp** [comment] 2018-06-02 12:27
Yes, that seems to work fine.

**Comment by sergv** [comment] 2018-06-11 22:31
Okay, with README fixed this should be a bit better. Still, I believe flycheck-haskell should strip lines starting `Warning:` from the output of `stack path`.

**Comment by sergv** [comment] 2019-08-24 22:18
I'm going to close this issue to clean up the issue tracker. If you feel the issue is not resolved then please either reopen it or create a new one.

**Closed by sergv** 2019-08-24 22:18 UTC
