### ISSUE TITLE
Different targets

### ISSUE THREAD

**Issue by Pitometsu** [flycheck/flycheck-haskell#76] opened 2017-09-20 12:52 UTC
When I working on `executable` sources, `flycheck` tell me that there are no some `build-dependencies` in `test-suite`, like:

```
Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: <command line>: cannot satisfy -package hspec-wai
    (use -v for more information)

Try installing a more recent version of haskell-stack-ghc, and please open a bug report if the issue persists in the latest release.  Thanks!
```
Or even:
```
Suspicious state from syntax checker haskell-hdevtools: Flycheck checker haskell-hdevtools returned non-zero exit code 1, but its output contained no errors: Cabal error: Encountered missing dependencies:
    hspec-wai -any, hspec-wai-json -any

Try installing a more recent version of haskell-hdevtools, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by Pitometsu** [comment] 2017-09-20 12:54
Shouldn't it check which target current file belongs to?

**Comment by sergv** [comment] 2017-09-20 15:42
Can you please provide a reproducible example?

As a general rule, flycheck-haskell does not distinguish between targets.
Instead, it uses build-depends packages from all targets of a cabal file
when checking project's files.

On Sep 20, 2017 3:54 PM, "Yuriy Pitomets" <notifications@github.com> wrote:

Shouldn't it check which target current file belongs to?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/flycheck/flycheck-haskell/issues/76#issuecomment-330842253>,
or mute the thread

**Comment by Pitometsu** [comment] 2017-10-20 17:34
Ok, solved by cleaning up stack file. However it still would be good to have option to build only required target for current file.

**Comment by sergv** [comment] 2017-11-07 09:02
Again, as I mentioned before, Haskell checkers in flycheck try to keep it simple by running compiler on the current file. This choice makes all checkers robust with respect to underlying build tools which may have different notions of build targets (cf `cabal` vs `stack`) and likely other quirks build systems tend to have. Adding targets will require significant changes to both `flycheck.el` and possibly `flycheck-haskell.el`, but it's not clear yet what benefits that would bring with regards to current simpler approach.

Therefore I'm closing this issue for now because I have no intention to fix it myself. However, I would be gland to see a PR that will incorporate handling of targets and I look forward to continue this discussion there.

**Closed by sergv** 2017-11-07 09:02 UTC

**Comment by aviaviavi** [comment] 2020-07-14 22:27
@Pitometsu could you describe what you did to "clean up your stack file"?

I'm using stack and am hitting this issue now, where I have a package in my `tests` target dependencies (tasty) that isn't present in my `executables` build targets (and shouldn't need to be). So in that situation, I'm getting: 

```
Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned 1, but its output contained no errors: <command line>: cannot satisfy -package tasty
    (use -v for more information)

Try installing a more recent version of haskell-stack-ghc, and please open a bug report if the issue persists in the latest release.  Thanks!
```

Is the only fix here to just add `tasty` to my executable target, just to appease flycheck, or am I missing something? Any pointers here is appreciated!
