### ISSUE TITLE
Honor "with-compiler" flag in cabal.config when doing flycheck-haskell-configure

### ISSUE THREAD

**Issue by rpglover64** [flycheck/flycheck-haskell#28] opened 2015-03-14 21:38 UTC
I have 3 different versions of GHC installed on my system currently: the one supported by my OS (7.6.3), the latest stable release (7.8.4), and the latest release candidate (7.10-rc1). I would like to choose which one to use on a per-project basis. using a project local cabal.config enables me to do so for most purposes, even without having a foo.cabal file.

**Comment by rpglover64** [comment] 2015-03-14 22:44
It looks like [this](https://gist.github.com/rpglover64/30bb21d04605ed0feb61) does it.

I make no claims about the quality of my change; it's a lot of copy/paste and some of the functions it duplicates could and probably should be abstracted.

**Comment by lunaryorn** [comment] 2015-04-04 13:05
@rpglover64  Sorry for the long delay.

This looks like a great addition to this package.  Would you mind to make a proper pull request out of your patch?  It'd make review and merging much easier for me.

**Comment by lunaryorn** [comment] 2015-05-28 19:07
Closing as duplicate of #29

**Closed by lunaryorn** 2015-05-28 19:07 UTC
Labels: enhancement
