### ISSUE TITLE
Flycheck with nix: Could not find module

### ISSUE THREAD

**Issue by rubenmoor** [flycheck/flycheck-haskell#88] opened 2018-05-26 00:02 UTC
I get the error "Could not find module" for a cabal project that has two executables and one library. The modules that can't be found are in the library of the same cabal project.

I use flycheck on nix with this emacs configuration:

    (setq flycheck-haskell-ghc-executable "/my/home/path/nix-ghc")

where `nix-ghc` is an executable shell script like this:

    #!/bin/sh
    nix-shell -I . --command "ghc $*"

As a temporary solution, I use `stack` now together with nix. This fixes my IDE while I can still build using nix without stack.

**Comment by rubenmoor** [comment] 2018-05-26 21:49
This is a link to a sample project - it contains a minimal cabal package with library and executable.

https://github.com/rubenmoor/haskell-nix-flycheck

I also put relevant config files of my emacs/nix setup in there (`config.el` and `nix-ghc`).

The bug description is in the README.md

**Comment by sergv** [comment] 2019-08-24 22:18
I'm going to close this issue to clean up the issue tracker. If you feel the issue is not resolved then please either reopen it or create a new one.

**Closed by sergv** 2019-08-24 22:18 UTC
