### ISSUE TITLE
weird output from haskell-hlint checker

### ISSUE THREAD

**Issue by vyorkin** [flycheck/flycheck-haskell#94] opened 2018-11-16 21:00 UTC
![image](https://user-images.githubusercontent.com/988849/48647010-b22a9b80-e9fb-11e8-97d3-f2f749f26901.png)

vs

![image](https://user-images.githubusercontent.com/988849/48647025-bd7dc700-e9fb-11e8-83f0-12b06371fd2d.png)

**Comment by sergv** [comment] 2018-11-17 10:05
Looks like a temporary file name slipped into the message. This will need to be fixed inside main flycheck repo as current project only gathers configuration parameters for checkers there.

**Comment by sergv** [comment] 2019-08-24 22:18
I'm going to close this issue to clean up the issue tracker. If you feel the issue is not resolved then please either reopen it or create a new one.

**Closed by sergv** 2019-08-24 22:18 UTC
