### ISSUE TITLE
no errors

### ISSUE THREAD

**Issue by kuribas** [flycheck/flycheck-haskell#81] opened 2017-11-26 20:37 UTC
Flycheck shows no errors, even when I enter garbage in the file.  I use ghc-8.2.2, and the latest flycheck-haskell and haskell-mode from melpa.

**Comment by kuribas** [comment] 2017-11-26 21:26
It seems to work for some of my projects, on not for others.

**Comment by sergv** [comment] 2017-11-26 21:59
@kuribas Thanks for your report. Can you provide a reproducible where it does not work?

**Comment by kuribas** [comment] 2017-11-27 06:52
https://github.com/kuribas/cubicbezier/tree/flycheck
It doesn't check Geom2D/CubicBezier/Basic.hs, which contains errors.

**Comment by kuribas** [comment] 2017-11-27 06:55
I know elisp, if I could find a entry point I could try debug it myself.  But it's hard because it fails without error.

**Comment by kuribas** [comment] 2017-11-27 19:41
running flycheck-compile shows that the error is in another file that it compiles before checking this file.  Perhaps flycheck-haskell could show why it has failed checking this file?

**Comment by sergv** [comment] 2017-11-27 22:34
Ah, if the error comes from another file then there is an explanation for that. You see, the flycheck currently doesn't show errors from other files. There are ideas and some moderate attempts to fix that, but it doesn't seem to be near its finish - https://github.com/flycheck/flycheck/issues/966. If you can lend a hand there it would be of tremendous help. In the mean time there is this general limitation that you get meaningful errors from the current buffer only.

**Comment by sergv** [comment] 2017-12-06 09:16
I'm closing this issue since it should be fixed in the `flycheck` repository, not in `flycheck-haskell`.

**Closed by sergv** 2017-12-06 09:16 UTC
